### ISSUE TITLE
Don't remove trailing whitespace

### ISSUE THREAD

**Issue by SBoudrias** [chalk/wrap-ansi#9]
Trailing whitespaces are currently deleted. This should probably not happen.

It's preventing me from using wrap-ansi inside Inquirer.js ATM.

**Comment by dthree** [comment]
@bcoe we should discuss this, as adding trailing whitespace might break other implementations.

For example, take the string `a b c d e`, wrapped on `3`, and for clarity we'll make `*` represent white-space. We can do one of two things:


```
// 1. Allow overflow for white-space only
a*b*
c*d*
e

// 2. Bump the beginning of the next line with white-space:
a*b
*c*
d*e
```

2 above is uglier, but it won't break anything. 1 above would seem to break things as it violates the expected width of the wrap.

What do you think?

**Comment by bcoe** [comment]
@dthree my gut would be that we should opt for option `.2`; especially when `hard` is enabled, we can never afford to overflow since tools like `cliui` and `yargs` use `wrap-ansi` for multi-column layout (columns would start to flow into each other).

Either approach taken, it's probably best to opt for a `major` bump I think?

**Comment by SBoudrias** [comment]
Maybe we could just keep the whitespace at the beginning and the end of the block?

**Comment by bcoe** [comment]
@SBoudrias this sounds reasonable :+1: if you have the time, could you send a failing test case perhaps? 

I'd love to see Inquirer using this, big fan :+1:

**Comment by dthree** [comment]
@bcoe I agree on both points.

@SBoudrias yeah - could you please give some examples to ensure we understand you correctly?

**Comment by SamVerschueren** [comment]
I think we have an issue in `log-update` now as well (reported here https://github.com/sindresorhus/log-update/issues/20). We started using `wrap-ansi` but because it trims all the whitespaces, some of the use cases are now foobar. I started to look into this but couldn't come up with a good solution yet. Maybe I should just do the PR (with what I have) and we can iterate from there?

// @sindresorhus

**Comment by sindresorhus** [comment]
> and we can iterate from there?

👍

**Comment by axe312ger** [comment]
Yes please make that configurable! <3 :)

**Comment by axe312ger** [comment]
thank you! 🙇
